//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCoreWcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformCountResponse", Namespace="http://schemas.datacontract.org/2004/07/Core.Responses")]
    internal partial class PerformCountResponse : object
    {
        
        private SampleCoreWcfService.PerformCountResponseBody BodyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SampleCoreWcfService.PerformCountResponseBody Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformCountResponseBody", Namespace="http://schemas.datacontract.org/2004/07/Core.Responses")]
    internal partial class PerformCountResponseBody : object
    {
        
        private int PerformCountResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PerformCountResult
        {
            get
            {
                return this.PerformCountResultField;
            }
            set
            {
                this.PerformCountResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformReverseResponse", Namespace="http://schemas.datacontract.org/2004/07/Core.Responses")]
    internal partial class PerformReverseResponse : object
    {
        
        private SampleCoreWcfService.PerformReverseResponseBody BodyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SampleCoreWcfService.PerformReverseResponseBody Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformReverseResponseBody", Namespace="http://schemas.datacontract.org/2004/07/Core.Responses")]
    internal partial class PerformReverseResponseBody : object
    {
        
        private string PerformReverseResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PerformReverseResult
        {
            get
            {
                return this.PerformReverseResultField;
            }
            set
            {
                this.PerformReverseResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleCoreWcfService.ISampleServiceExtended")]
    internal interface ISampleServiceExtended
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/PerformCount", ReplyAction="http://tempuri.org/ISampleService/PerformCountResponse")]
        System.Threading.Tasks.Task<int> PerformCountAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/PerformReverse", ReplyAction="http://tempuri.org/ISampleService/PerformReverseResponse")]
        System.Threading.Tasks.Task<string> PerformReverseAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceExtended/PerformCountWithAsmxResponseFormat", ReplyAction="http://tempuri.org/ISampleServiceExtended/PerformCountWithAsmxResponseFormatRespo" +
            "nse")]
        System.Threading.Tasks.Task<SampleCoreWcfService.PerformCountResponse> PerformCountWithAsmxResponseFormatAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceExtended/PerformReverseWithAsmxResponseFormat", ReplyAction="http://tempuri.org/ISampleServiceExtended/PerformReverseWithAsmxResponseFormatRes" +
            "ponse")]
        System.Threading.Tasks.Task<SampleCoreWcfService.PerformReverseResponse> PerformReverseWithAsmxResponseFormatAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface ISampleServiceExtendedChannel : SampleCoreWcfService.ISampleServiceExtended, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class SampleServiceExtendedClient : System.ServiceModel.ClientBase<SampleCoreWcfService.ISampleServiceExtended>, SampleCoreWcfService.ISampleServiceExtended
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SampleServiceExtendedClient() : 
                base(SampleServiceExtendedClient.GetDefaultBinding(), SampleServiceExtendedClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISampleServiceExtended.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceExtendedClient(EndpointConfiguration endpointConfiguration) : 
                base(SampleServiceExtendedClient.GetBindingForEndpoint(endpointConfiguration), SampleServiceExtendedClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceExtendedClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SampleServiceExtendedClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceExtendedClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SampleServiceExtendedClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceExtendedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> PerformCountAsync(string input)
        {
            return base.Channel.PerformCountAsync(input);
        }
        
        public System.Threading.Tasks.Task<string> PerformReverseAsync(string input)
        {
            return base.Channel.PerformReverseAsync(input);
        }
        
        public System.Threading.Tasks.Task<SampleCoreWcfService.PerformCountResponse> PerformCountWithAsmxResponseFormatAsync(string input)
        {
            return base.Channel.PerformCountWithAsmxResponseFormatAsync(input);
        }
        
        public System.Threading.Tasks.Task<SampleCoreWcfService.PerformReverseResponse> PerformReverseWithAsmxResponseFormatAsync(string input)
        {
            return base.Channel.PerformReverseWithAsmxResponseFormatAsync(input);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISampleServiceExtended))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISampleServiceExtended))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7107/SampleCoreWcfService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SampleServiceExtendedClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISampleServiceExtended);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SampleServiceExtendedClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISampleServiceExtended);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISampleServiceExtended,
        }
    }
}
